// CHAPTER 2 -- GRAMMAR


// try catch statement
// catch exceptions thrown by the block
var x = 0;
try {
    console.log(x + y);
} catch (ReferenceError) {
    console.log("There was an error");
}
